Semantics
foxraisa/otus-css-Spiridonova-old pull request #1
Opened 2023-02-15 10:23 UTC by foxraisa

2023-02-15 13:05 UTC, lipa88-mk requested changes
Хорошая работа! Нужно еще пройти по заголовкам, тк у них сейчас нет структуры. Плюс было бы хорошо придерживаться одинаковых отступов у вложенных элементов. И рекомендую посмотреть статейку в канале Слак по именованию классов, чтобы поправить имена вроде `navHead`

2023-02-15 13:05 UTC, lipa88-mk commented on index.html
> +    <h1>Katya Mills</h1>
Заголовок 1 уровня уже используется, тут и далее - заголовки 2 и 3, поправьте

2023-02-15 13:05 UTC, lipa88-mk commented on index.html
> +        <h2>Biography</h2>
Всё таки мы сначала говорим что это часть про биографию, а потом чья она - Кати Милс, Поэтому порядок заголовков другой)

2023-02-15 13:05 UTC, lipa88-mk commented on index.html
> +        <h2>Designers</h2>
Тут уровень заголовка верный, но потом тогда не 2 уровень, ведь имена - это подчасти заголовка Дизайнеры.

2023-02-15 13:05 UTC, lipa88-mk commented on index.html
> +            <h3>Design Strategy / Marketing</h3>
Вот ту нужно подумать - это заголовок или все таки контент?

2023-02-15 13:05 UTC, lipa88-mk commented on index.html
> +        <h2>Website
тут тоже не уровень 2 заголовка

2023-02-15 15:24 UTC, foxraisa commented on index.html
> +    <h1>Katya Mills</h1>
А почему так, если они одинаковы по шрифту и по размеру шрифта?

2023-02-19 09:01 UTC, lipa88-mk requested changes
Как вижу, по структуре заголовков все осталось почти так же. А все места, где я написала комментарии отмечены как Resolved, что не верно. "Решено" - значит, что это как-то исправлено. Проверьте, все ли ваши комиты сейчас в пул реквесте? Возможно вы что-то забыли добавить?

2023-02-19 09:01 UTC, lipa88-mk commented on index.html
> +    <h1>Katya Mills</h1>
Потому что оформление - это другой шаг и тут оно не важно

2023-02-19 09:01 UTC, lipa88-mk commented on index.html
> +    <h1>Katya Mills</h1>
Вижу, что по заголовкам пока что ситуация не сильно поменялась. Есть какие-то вопросы?

2023-02-19 09:01 UTC, lipa88-mk commented on index.html
> +    <h1>Katya Mills</h1>
ЗЫ: не отмечайте пожалуйста как Resolved то, что вы не исправили)

2023-02-19 09:01 UTC, lipa88-mk commented on index.html
> +        <h2>Biography</h2>
Порядок заголовков тут другой - сначала Биография, потом имя. Уровни заголовков тоже будут другие

2023-02-19 17:38 UTC, foxraisa commented on index.html
> +    <h1>Katya Mills</h1>
Ок, но там давно уже не просто h1. Все коммиты добавлены. Как-то тогда не понимаю в чем проблема? 
Там код уже другой: 

<section>
        <h1 id="title-page"> Mod Studio </h1>
        <h2 id="subtitle-page">Modern Web Studio</h2>
        <img src="img/main-box-weather-room.jpg" alt="Weather room">
    </section>

    <section>
        <h3 class="katya-mills_header"> Biography </h3>
        <h3 class="katya-mills_name"> Katya Mills </h3>
        <img src="img/katya-mills.jpg" alt="Katya Mills">
        <p class="katya-mills_skills">  Art Director Scenography / Styling / Creative Photography / Design</p>
        <p class="katya-mills_text">“The more I deal with the work as something that is my own, as something that is personal, the more successful it is.”</p>
    </section>

2023-02-20 16:18 UTC, lipa88-mk requested changes
Расставьте уровни заголовков таким образом и можно будет закончить на этом :)

2023-02-20 16:18 UTC, lipa88-mk commented on index.html
> +        <h3 class="katya-mills_header"> Biography </h3>
Это 2

2023-02-20 16:18 UTC, lipa88-mk commented on index.html
> +        <h3 class="disigners_header">Designers</h3>
Это 2

2023-02-20 16:18 UTC, lipa88-mk commented on index.html
> +            <p class="disigners_img-text">
Это скорее див, тк внутри группа тегов, не просто параграф. Внутри картинка, подзаголовок 3 и два параграфа - все это отдельные смысловые элементы, не один параграф.

2023-02-20 16:18 UTC, lipa88-mk commented on index.html
> +        <h4 class="testimonials_header">Testimonials</h4>
Это 2 уровень

2023-02-20 16:18 UTC, lipa88-mk commented on index.html
> +        <h5 class="strong-points_header">Strong points</h5>
Это 2

2023-02-20 16:18 UTC, lipa88-mk commented on index.html
> +        <h6 class="strong-points_strengths-navbar-header">  Strengths</h6>
Это 3

2023-02-22 18:07 UTC, merged